### ISSUE TITLE
Sugestões de melhorias.

### ISSUE THREAD

**Issue by JhoanDev** [classroom-ufersa/busca_de_strings_com_busca_sequencial#2]
1- não colocar limites de funcionários, ao invés disso façam alocação dinâmica por exemplo utilizando realloc.
```
    int op, documento, count_fun = 0;
    int nomeValido = 0;

    char nome[100], cargo[50];

    Funcionario *funcionario[fun];
```

2- Calcular apenas o tempo de execução das funçoes de busca e nao do programa inteiro.

```
    clock_t inicio = clock();
    double tempo = (double)(clock() - inicio) / CLOCKS_PER_SEC;
    tempo = tempo * 1000; // milisegundos
```
3- Dar free nas alocações ao fim do programa.

**Comment by roscibely** [comment]
@diegonascimento2023 @Oluaphenrique considerar os pontos destacados por Jhoan e editar o código.
